/* C code for program sncdante8IOC, generated by snc from ../sncdante8IOC.stt */
#include <string.h>
#include <stddef.h>
#include <stdio.h>
#include <limits.h>

#include "seq_snc.h"
# line 14 "../sncdante8IOC.stt"

#include <math.h>
#include <stdlib.h>
#include <unistd.h>
#include <time.h>
#include <sys/stat.h>
#include <errno.h>


static FILE *general_path_save_file;



/* Variable declarations */
# line 30 "../sncdante8IOC.stt"
static	string output_path;
# line 34 "../sncdante8IOC.stt"
static	char name_server[40];
# line 36 "../sncdante8IOC.stt"
static	int detector_type;
# line 40 "../sncdante8IOC.stt"
static	string name_file;
# line 44 "../sncdante8IOC.stt"
static	int num_export;
# line 48 "../sncdante8IOC.stt"
static	int nord_data;
# line 56 "../sncdante8IOC.stt"
static	int data[100];
# line 61 "../sncdante8IOC.stt"
static	string temp_string;
# line 62 "../sncdante8IOC.stt"
static	char full_save_path[120];
# line 63 "../sncdante8IOC.stt"
static	char full_save_file[180];
# line 64 "../sncdante8IOC.stt"
static	int k;


/* Function declarations */

#define seqg_var (*(struct seqg_vars *const *)seqg_env)

/* Program init func */
static void seqg_init(PROG_ID seqg_env)
{
}

/****** Code for state "init" in state set "save_data" ******/

/* Event function for state "init" in state set "save_data" */
static seqBool seqg_event_save_data_0_init(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "init" in state set "save_data" */
static void seqg_action_save_data_0_init(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	}
}

/****** Code for state "idle" in state set "save_data" ******/

/* Event function for state "idle" in state set "save_data" */
static seqBool seqg_event_save_data_0_idle(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 78 "../sncdante8IOC.stt"
	if (num_export == 1)
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "idle" in state set "save_data" */
static void seqg_action_save_data_0_idle(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	}
}

/****** Code for state "prep" in state set "save_data" ******/

/* Event function for state "prep" in state set "save_data" */
static seqBool seqg_event_save_data_0_prep(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		*seqg_pnst = 3;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "prep" in state set "save_data" */
static void seqg_action_save_data_0_prep(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 87 "../sncdante8IOC.stt"
			printf("Prepare file\n");
# line 88 "../sncdante8IOC.stt"
			strcpy(name_server, seq_macValueGet(seqg_env, "server"));
# line 90 "../sncdante8IOC.stt"
			printf("Server: %s\n", name_server);
# line 91 "../sncdante8IOC.stt"
			sprintf(full_save_path, "/home/%s/%s", name_server, output_path);
# line 92 "../sncdante8IOC.stt"
			printf("path to save: %s\n", full_save_path);
		}
		return;
	}
}

/****** Code for state "generate_file" in state set "save_data" ******/

/* Event function for state "generate_file" in state set "save_data" */
static seqBool seqg_event_save_data_0_generate_file(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		*seqg_pnst = 4;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "generate_file" in state set "save_data" */
static void seqg_action_save_data_0_generate_file(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 100 "../sncdante8IOC.stt"
			printf("Generate file\n");
# line 101 "../sncdante8IOC.stt"
			seq_pvGetTmo(seqg_env, 2/*name_file*/, SYNC, DEFAULT_TIMEOUT);
# line 102 "../sncdante8IOC.stt"
			sprintf(full_save_file, "%s/%s", full_save_path, name_file);
# line 103 "../sncdante8IOC.stt"
			printf("File Out: %s\n", name_file);
# line 104 "../sncdante8IOC.stt"
			printf("File to Save: %s\n", full_save_file);
		}
		return;
	}
}

/****** Code for state "export_data" in state set "save_data" ******/

/* Event function for state "export_data" in state set "save_data" */
static seqBool seqg_event_save_data_0_export_data(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "export_data" in state set "save_data" */
static void seqg_action_save_data_0_export_data(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 112 "../sncdante8IOC.stt"
			printf("Export Data file\n");
# line 113 "../sncdante8IOC.stt"
			general_path_save_file = fopen(full_save_file, "w");
# line 115 "../sncdante8IOC.stt"
			if (general_path_save_file == NULL)
			{
# line 116 "../sncdante8IOC.stt"
				printf("Scan: ERROR - Cannot open file %s: %s\n", full_save_file, strerror(errno));
			}
			else
			{
# line 118 "../sncdante8IOC.stt"
				seq_pvGetTmo(seqg_env, 5/*data*/, SYNC, DEFAULT_TIMEOUT);
# line 119 "../sncdante8IOC.stt"
				seq_pvGetTmo(seqg_env, 4/*nord_data*/, SYNC, DEFAULT_TIMEOUT);
# line 120 "../sncdante8IOC.stt"
				for (k = 0; k < nord_data - 1; k++)
				{
# line 121 "../sncdante8IOC.stt"
					fprintf(general_path_save_file, "%d\n", data[k]);
				}
# line 123 "../sncdante8IOC.stt"
				fflush(general_path_save_file);
			}
# line 125 "../sncdante8IOC.stt"
			num_export = 0;
# line 126 "../sncdante8IOC.stt"
			seq_pvPutTmo(seqg_env, 3/*num_export*/, SYNC, DEFAULT_TIMEOUT);
# line 127 "../sncdante8IOC.stt"
			fclose(general_path_save_file);
		}
		return;
	}
}

#undef seqg_var

/************************ Tables ************************/

/* Channel table */
static seqChan seqg_chans[] = {
	/* chName, offset, varName, varType, count, eventNum, efId, monitored, queueSize, queueIndex */
	{"{user}:scan:filepath", (size_t)&output_path, "output_path", P_STRING, 1, 1, 0, 1, 0, 0},
	{"{user}_{card}_{axis}:type", (size_t)&detector_type, "detector_type", P_INT, 1, 2, 0, 1, 0, 0},
	{"{user}_{card}_{axis}:dataout", (size_t)&name_file, "name_file", P_STRING, 1, 3, 0, 1, 0, 0},
	{"{user}_{card}_{axis}:status", (size_t)&num_export, "num_export", P_INT, 1, 4, 0, 1, 0, 0},
	{"{user}_{card}_{axis}:data.NORD", (size_t)&nord_data, "nord_data", P_INT, 1, 5, 0, 1, 0, 0},
	{"{user}_{card}_{axis}:data", (size_t)&data, "data", P_INT, 100, 6, 0, 1, 0, 0},
};

/* Event masks for state set "save_data" */
static const seqMask seqg_mask_save_data_0_init[] = {
	0x00000000,
};
static const seqMask seqg_mask_save_data_0_idle[] = {
	0x00000010,
};
static const seqMask seqg_mask_save_data_0_prep[] = {
	0x00000000,
};
static const seqMask seqg_mask_save_data_0_generate_file[] = {
	0x00000000,
};
static const seqMask seqg_mask_save_data_0_export_data[] = {
	0x00000000,
};

/* State table for state set "save_data" */
static seqState seqg_states_save_data[] = {
	{
	/* state name */        "init",
	/* action function */   seqg_action_save_data_0_init,
	/* event function */    seqg_event_save_data_0_init,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_save_data_0_init,
	/* state options */     (0)
	},
	{
	/* state name */        "idle",
	/* action function */   seqg_action_save_data_0_idle,
	/* event function */    seqg_event_save_data_0_idle,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_save_data_0_idle,
	/* state options */     (0)
	},
	{
	/* state name */        "prep",
	/* action function */   seqg_action_save_data_0_prep,
	/* event function */    seqg_event_save_data_0_prep,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_save_data_0_prep,
	/* state options */     (0)
	},
	{
	/* state name */        "generate_file",
	/* action function */   seqg_action_save_data_0_generate_file,
	/* event function */    seqg_event_save_data_0_generate_file,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_save_data_0_generate_file,
	/* state options */     (0)
	},
	{
	/* state name */        "export_data",
	/* action function */   seqg_action_save_data_0_export_data,
	/* event function */    seqg_event_save_data_0_export_data,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_save_data_0_export_data,
	/* state options */     (0)
	},
};

/* State set table */
static seqSS seqg_statesets[] = {
	{
	/* state set name */    "save_data",
	/* states */            seqg_states_save_data,
	/* number of states */  5
	},
};

/* Program table (global) */
seqProgram sncdante8IOC = {
	/* magic number */      2002009,
	/* program name */      "sncdante8IOC",
	/* channels */          seqg_chans,
	/* num. channels */     6,
	/* state sets */        seqg_statesets,
	/* num. state sets */   1,
	/* user var size */     0,
	/* param */             "",
	/* num. event flags */  0,
	/* encoded options */   (0 | OPT_CONN | OPT_NEWEF),
	/* init func */         seqg_init,
	/* entry func */        0,
	/* exit func */         0,
	/* num. queues */       0
};

/* Register sequencer commands and program */
#include "epicsExport.h"
static void sncdante8IOCRegistrar (void) {
    seqRegisterSequencerCommands();
    seqRegisterSequencerProgram (&sncdante8IOC);
}
epicsExportRegistrar(sncdante8IOCRegistrar);
